### ISSUE TITLE
Error on library usage

### ISSUE THREAD

**Issue by mubinahmed** [jbouduin/hal-rest-client#32]
Hi,

Can I know if this library is still in working condition. I used it in one of my project, and have errors with the build. Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/3035489/212468174-8685e59a-c7cf-408a-a0f9-4b6ad6c396e2.png)

**Comment by jbouduin** [comment]
Hello,

to answer your question: yes, the library is in working condition. I am using it everyday.
The class UriData is exported, but marked as internal in the code. That causes the error to show when opening the d.ts file as seen in the screenshot. It should however not prevent the usage of the library. 

Nevertheless, it is an error to have UriData in the interface definition. I'll correct it A.S.A.P.

thx for reporting
Johan
